# Generated by Django 4.2.7 on 2026-02-18 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(db_index=True, max_length=500)),
                ("referer", models.CharField(blank=True, max_length=500)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "session_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["path", "created_at"],
                        name="analytics_p_path_53ae0e_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="analytics_p_created_4c2b45_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("click", "Click"),
                            ("download", "Download"),
                            ("form_submit", "Form Submit"),
                            ("video_play", "Video Play"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=50,
                    ),
                ),
                ("event_name", models.CharField(db_index=True, max_length=200)),
                ("path", models.CharField(blank=True, max_length=500)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional event data"
                    ),
                ),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "session_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="analytics_e_event_t_ef40a5_idx",
                    ),
                    models.Index(
                        fields=["event_name", "created_at"],
                        name="analytics_e_event_n_0a0c8f_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="analytics_e_created_7b5fb3_idx"
                    ),
                ],
            },
        ),
    ]
